// 自动生成：基底装备数据（来自 armor.txt + objects.json）
// 生成脚本 _build_base_data.py；M01-M09 召唤物装备已排除。
window.BASE_ITEMS = [
 {
  "code": "cap",
  "name_en": "Cap",
  "name_zh": "便帽",
  "name_zh_tw": "便帽",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "普通",
  "durability": 12,
  "defense_min": 3,
  "defense_max": 5,
  "defense_avg": 4.0,
  "reqstr": 0,
  "qlvl": 1,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/cap_hat.webp"
 },
 {
  "code": "skp",
  "name_en": "Skull Cap",
  "name_zh": "颅帽",
  "name_zh_tw": "顱帽",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "普通",
  "durability": 18,
  "defense_min": 8,
  "defense_max": 11,
  "defense_avg": 9.5,
  "reqstr": 15,
  "qlvl": 5,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/skull_cap.webp"
 },
 {
  "code": "hlm",
  "name_en": "Helm",
  "name_zh": "头盔",
  "name_zh_tw": "頭盔",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "普通",
  "durability": 24,
  "defense_min": 15,
  "defense_max": 18,
  "defense_avg": 16.5,
  "reqstr": 26,
  "qlvl": 11,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/helm.webp"
 },
 {
  "code": "fhl",
  "name_en": "Full Helm",
  "name_zh": "全罩盔",
  "name_zh_tw": "全罩盔",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "普通",
  "durability": 30,
  "defense_min": 23,
  "defense_max": 26,
  "defense_avg": 24.5,
  "reqstr": 41,
  "qlvl": 15,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/full_helm.webp"
 },
 {
  "code": "ghm",
  "name_en": "Great Helm",
  "name_zh": "重盔",
  "name_zh_tw": "重盔",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "普通",
  "durability": 40,
  "defense_min": 30,
  "defense_max": 35,
  "defense_avg": 32.5,
  "reqstr": 63,
  "qlvl": 23,
  "max_sockets": 3,
  "sockets3": "2/2/3",
  "speed": 0,
  "img": "assets/equipment/great_helm.webp"
 },
 {
  "code": "crn",
  "name_en": "Crown",
  "name_zh": "王冠",
  "name_zh_tw": "王冠",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "普通",
  "durability": 50,
  "defense_min": 25,
  "defense_max": 45,
  "defense_avg": 35.0,
  "reqstr": 55,
  "qlvl": 29,
  "max_sockets": 3,
  "sockets3": "2/2/3",
  "speed": 0,
  "img": "assets/equipment/crown.webp"
 },
 {
  "code": "msk",
  "name_en": "Mask",
  "name_zh": "面具",
  "name_zh_tw": "面具",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "普通",
  "durability": 20,
  "defense_min": 9,
  "defense_max": 27,
  "defense_avg": 18.0,
  "reqstr": 23,
  "qlvl": 19,
  "max_sockets": 3,
  "sockets3": "2/2/3",
  "speed": 0,
  "img": "assets/equipment/mask.webp"
 },
 {
  "code": "qui",
  "name_en": "Quilted Armor",
  "name_zh": "棉布甲",
  "name_zh_tw": "棉布甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 20,
  "defense_min": 8,
  "defense_max": 11,
  "defense_avg": 9.5,
  "reqstr": 12,
  "qlvl": 1,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/quilted_armor.webp"
 },
 {
  "code": "lea",
  "name_en": "Leather Armor",
  "name_zh": "皮革甲",
  "name_zh_tw": "皮革甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 24,
  "defense_min": 14,
  "defense_max": 17,
  "defense_avg": 15.5,
  "reqstr": 15,
  "qlvl": 3,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/leather_armor.webp"
 },
 {
  "code": "hla",
  "name_en": "Hard Leather Armor",
  "name_zh": "硬皮甲",
  "name_zh_tw": "硬皮甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 28,
  "defense_min": 21,
  "defense_max": 24,
  "defense_avg": 22.5,
  "reqstr": 20,
  "qlvl": 5,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/hard_leather_armor.webp"
 },
 {
  "code": "stu",
  "name_en": "Studded Leather",
  "name_zh": "镶钉皮甲",
  "name_zh_tw": "鑲釘皮甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 32,
  "defense_min": 32,
  "defense_max": 35,
  "defense_avg": 33.5,
  "reqstr": 27,
  "qlvl": 8,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/studded_leather.webp"
 },
 {
  "code": "rng",
  "name_en": "Ring Mail",
  "name_zh": "环甲",
  "name_zh_tw": "環甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 26,
  "defense_min": 45,
  "defense_max": 48,
  "defense_avg": 46.5,
  "reqstr": 36,
  "qlvl": 11,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 5,
  "img": "assets/equipment/ring_mail.webp"
 },
 {
  "code": "scl",
  "name_en": "Scale Mail",
  "name_zh": "鳞甲",
  "name_zh_tw": "鱗甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 36,
  "defense_min": 57,
  "defense_max": 60,
  "defense_avg": 58.5,
  "reqstr": 44,
  "qlvl": 13,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 10,
  "img": "assets/equipment/scale_mail.webp"
 },
 {
  "code": "chn",
  "name_en": "Chain Mail",
  "name_zh": "锁链甲",
  "name_zh_tw": "鎖鍊甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 45,
  "defense_min": 72,
  "defense_max": 75,
  "defense_avg": 73.5,
  "reqstr": 48,
  "qlvl": 15,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 5,
  "img": "assets/equipment/chain_mail.webp"
 },
 {
  "code": "brs",
  "name_en": "Breast Plate",
  "name_zh": "胸铠",
  "name_zh_tw": "胸鎧",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 50,
  "defense_min": 65,
  "defense_max": 68,
  "defense_avg": 66.5,
  "reqstr": 30,
  "qlvl": 18,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 0,
  "img": "assets/equipment/breast_plate.webp"
 },
 {
  "code": "spl",
  "name_en": "Splint Mail",
  "name_zh": "板甲",
  "name_zh_tw": "板甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 30,
  "defense_min": 90,
  "defense_max": 95,
  "defense_avg": 92.5,
  "reqstr": 51,
  "qlvl": 20,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 5,
  "img": "assets/equipment/splint_mail.webp"
 },
 {
  "code": "plt",
  "name_en": "Plate Mail",
  "name_zh": "铠甲",
  "name_zh_tw": "鎧甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 60,
  "defense_min": 108,
  "defense_max": 116,
  "defense_avg": 112.0,
  "reqstr": 65,
  "qlvl": 24,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 10,
  "img": "assets/equipment/plate_mail.webp"
 },
 {
  "code": "fld",
  "name_en": "Field Plate",
  "name_zh": "野战铠甲",
  "name_zh_tw": "野戰鎧甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 48,
  "defense_min": 101,
  "defense_max": 105,
  "defense_avg": 103.0,
  "reqstr": 55,
  "qlvl": 28,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 5,
  "img": "assets/equipment/field_plate.webp"
 },
 {
  "code": "gth",
  "name_en": "Gothic Plate",
  "name_zh": "哥德铠甲",
  "name_zh_tw": "哥德鎧甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 55,
  "defense_min": 128,
  "defense_max": 135,
  "defense_avg": 131.5,
  "reqstr": 70,
  "qlvl": 32,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 5,
  "img": "assets/equipment/gothic_plate.webp"
 },
 {
  "code": "ful",
  "name_en": "Full Plate Mail",
  "name_zh": "全身铠甲",
  "name_zh_tw": "全身鎧甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 70,
  "defense_min": 150,
  "defense_max": 161,
  "defense_avg": 155.5,
  "reqstr": 80,
  "qlvl": 37,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 10,
  "img": "assets/equipment/full_plate_mail.webp"
 },
 {
  "code": "aar",
  "name_en": "Ancient Armor",
  "name_zh": "上古铠甲",
  "name_zh_tw": "上古鎧甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 60,
  "defense_min": 218,
  "defense_max": 233,
  "defense_avg": 225.5,
  "reqstr": 100,
  "qlvl": 40,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 5,
  "img": "assets/equipment/ancient_armor.webp"
 },
 {
  "code": "ltp",
  "name_en": "Light Plate",
  "name_zh": "轻型铠甲",
  "name_zh_tw": "輕型鎧甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "普通",
  "durability": 60,
  "defense_min": 90,
  "defense_max": 107,
  "defense_avg": 98.5,
  "reqstr": 41,
  "qlvl": 35,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 0,
  "img": "assets/equipment/light_plate.webp"
 },
 {
  "code": "buc",
  "name_en": "Buckler",
  "name_zh": "小圆盾",
  "name_zh_tw": "小圓盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "普通",
  "durability": 12,
  "defense_min": 4,
  "defense_max": 6,
  "defense_avg": 5.0,
  "reqstr": 12,
  "qlvl": 1,
  "max_sockets": 1,
  "sockets3": "1/1/1",
  "speed": 0,
  "img": "assets/equipment/buckler.webp"
 },
 {
  "code": "sml",
  "name_en": "Small Shield",
  "name_zh": "小型盾",
  "name_zh_tw": "小型盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "普通",
  "durability": 16,
  "defense_min": 8,
  "defense_max": 10,
  "defense_avg": 9.0,
  "reqstr": 22,
  "qlvl": 5,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/small_shield.webp"
 },
 {
  "code": "lrg",
  "name_en": "Large Shield",
  "name_zh": "大型盾",
  "name_zh_tw": "大型盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "普通",
  "durability": 24,
  "defense_min": 12,
  "defense_max": 14,
  "defense_avg": 13.0,
  "reqstr": 34,
  "qlvl": 11,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 5,
  "img": "assets/equipment/large_shield.webp"
 },
 {
  "code": "kit",
  "name_en": "Kite Shield",
  "name_zh": "鸢盾",
  "name_zh_tw": "鳶盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "普通",
  "durability": 30,
  "defense_min": 16,
  "defense_max": 18,
  "defense_avg": 17.0,
  "reqstr": 47,
  "qlvl": 15,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 0,
  "img": "assets/equipment/kite_shield.webp"
 },
 {
  "code": "tow",
  "name_en": "Tower Shield",
  "name_zh": "塔盾",
  "name_zh_tw": "塔盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "普通",
  "durability": 60,
  "defense_min": 22,
  "defense_max": 25,
  "defense_avg": 23.5,
  "reqstr": 75,
  "qlvl": 22,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 10,
  "img": "assets/equipment/tower_shield.webp"
 },
 {
  "code": "gts",
  "name_en": "Gothic Shield",
  "name_zh": "哥德盾",
  "name_zh_tw": "哥德盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "普通",
  "durability": 40,
  "defense_min": 30,
  "defense_max": 35,
  "defense_avg": 32.5,
  "reqstr": 60,
  "qlvl": 30,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 5,
  "img": "assets/equipment/gothic_shield.webp"
 },
 {
  "code": "lgl",
  "name_en": "Leather Gloves",
  "name_zh": "皮革手套",
  "name_zh_tw": "皮革手套",
  "category": "手套",
  "type_raw": "glov",
  "tier": "普通",
  "durability": 12,
  "defense_min": 2,
  "defense_max": 3,
  "defense_avg": 2.5,
  "reqstr": 0,
  "qlvl": 3,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/gloves_l.webp"
 },
 {
  "code": "vgl",
  "name_en": "Heavy Gloves",
  "name_zh": "厚皮手套",
  "name_zh_tw": "厚皮手套",
  "category": "手套",
  "type_raw": "glov",
  "tier": "普通",
  "durability": 14,
  "defense_min": 5,
  "defense_max": 6,
  "defense_avg": 5.5,
  "reqstr": 0,
  "qlvl": 7,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/heavy_gloves.webp"
 },
 {
  "code": "mgl",
  "name_en": "Chain Gloves",
  "name_zh": "炼甲手套",
  "name_zh_tw": "鍊甲手套",
  "category": "手套",
  "type_raw": "glov",
  "tier": "普通",
  "durability": 16,
  "defense_min": 8,
  "defense_max": 9,
  "defense_avg": 8.5,
  "reqstr": 25,
  "qlvl": 12,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/bracers_m.webp"
 },
 {
  "code": "tgl",
  "name_en": "Light Gauntlets",
  "name_zh": "轻型护手",
  "name_zh_tw": "輕型護手",
  "category": "手套",
  "type_raw": "glov",
  "tier": "普通",
  "durability": 18,
  "defense_min": 9,
  "defense_max": 11,
  "defense_avg": 10.0,
  "reqstr": 45,
  "qlvl": 20,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/light_gauntlets.webp"
 },
 {
  "code": "hgl",
  "name_en": "Gauntlets",
  "name_zh": "钢铁护手",
  "name_zh_tw": "鋼鐵護手",
  "category": "手套",
  "type_raw": "glov",
  "tier": "普通",
  "durability": 24,
  "defense_min": 12,
  "defense_max": 15,
  "defense_avg": 13.5,
  "reqstr": 60,
  "qlvl": 27,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/gaunlets_h.webp"
 },
 {
  "code": "lbt",
  "name_en": "Boots",
  "name_zh": "皮靴",
  "name_zh_tw": "皮靴",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "普通",
  "durability": 12,
  "defense_min": 2,
  "defense_max": 3,
  "defense_avg": 2.5,
  "reqstr": 0,
  "qlvl": 3,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/leather_boots.webp"
 },
 {
  "code": "vbt",
  "name_en": "Heavy Boots",
  "name_zh": "重靴",
  "name_zh_tw": "重靴",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "普通",
  "durability": 14,
  "defense_min": 5,
  "defense_max": 6,
  "defense_avg": 5.5,
  "reqstr": 18,
  "qlvl": 7,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/heavy_boots.webp"
 },
 {
  "code": "mbt",
  "name_en": "Chain Boots",
  "name_zh": "锁链靴",
  "name_zh_tw": "鎖鍊靴",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "普通",
  "durability": 16,
  "defense_min": 8,
  "defense_max": 9,
  "defense_avg": 8.5,
  "reqstr": 30,
  "qlvl": 12,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/chain_boots.webp"
 },
 {
  "code": "tbt",
  "name_en": "Light Plated Boots",
  "name_zh": "轻铠靴",
  "name_zh_tw": "輕鎧靴",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "普通",
  "durability": 18,
  "defense_min": 9,
  "defense_max": 11,
  "defense_avg": 10.0,
  "reqstr": 50,
  "qlvl": 20,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/light_plate_boots.webp"
 },
 {
  "code": "hbt",
  "name_en": "Greaves",
  "name_zh": "护胫",
  "name_zh_tw": "護脛",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "普通",
  "durability": 24,
  "defense_min": 12,
  "defense_max": 15,
  "defense_avg": 13.5,
  "reqstr": 70,
  "qlvl": 27,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/plate_boots.webp"
 },
 {
  "code": "lbl",
  "name_en": "Sash",
  "name_zh": "束带",
  "name_zh_tw": "束帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "普通",
  "durability": 12,
  "defense_min": 2,
  "defense_max": 2,
  "defense_avg": 2.0,
  "reqstr": 0,
  "qlvl": 3,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/sash_l.webp"
 },
 {
  "code": "vbl",
  "name_en": "Light Belt",
  "name_zh": "轻腰带",
  "name_zh_tw": "輕腰帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "普通",
  "durability": 14,
  "defense_min": 3,
  "defense_max": 3,
  "defense_avg": 3.0,
  "reqstr": 0,
  "qlvl": 7,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/light_belt.webp"
 },
 {
  "code": "mbl",
  "name_en": "Belt",
  "name_zh": "腰带",
  "name_zh_tw": "腰帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "普通",
  "durability": 16,
  "defense_min": 5,
  "defense_max": 5,
  "defense_avg": 5.0,
  "reqstr": 25,
  "qlvl": 12,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/belt_m.webp"
 },
 {
  "code": "tbl",
  "name_en": "Heavy Belt",
  "name_zh": "厚腰带",
  "name_zh_tw": "厚腰帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "普通",
  "durability": 18,
  "defense_min": 6,
  "defense_max": 6,
  "defense_avg": 6.0,
  "reqstr": 45,
  "qlvl": 20,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/heavy_belt.webp"
 },
 {
  "code": "hbl",
  "name_en": "Plated Belt",
  "name_zh": "铠甲腰带",
  "name_zh_tw": "鎧甲腰帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "普通",
  "durability": 24,
  "defense_min": 8,
  "defense_max": 11,
  "defense_avg": 9.5,
  "reqstr": 60,
  "qlvl": 27,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/girdle_h.webp"
 },
 {
  "code": "bhm",
  "name_en": "Bone Helm",
  "name_zh": "骸骨头盔",
  "name_zh_tw": "骸骨頭盔",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "普通",
  "durability": 40,
  "defense_min": 33,
  "defense_max": 36,
  "defense_avg": 34.5,
  "reqstr": 25,
  "qlvl": 22,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/bone_helm.webp"
 },
 {
  "code": "bsh",
  "name_en": "Bone Shield",
  "name_zh": "骨盾",
  "name_zh_tw": "骨盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "普通",
  "durability": 40,
  "defense_min": 10,
  "defense_max": 30,
  "defense_avg": 20.0,
  "reqstr": 25,
  "qlvl": 19,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/bone_shield.webp"
 },
 {
  "code": "spk",
  "name_en": "Spiked Shield",
  "name_zh": "尖刺盾",
  "name_zh_tw": "尖刺盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "普通",
  "durability": 40,
  "defense_min": 15,
  "defense_max": 25,
  "defense_avg": 20.0,
  "reqstr": 30,
  "qlvl": 11,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/spiked_shield.webp"
 },
 {
  "code": "xap",
  "name_en": "War Hat",
  "name_zh": "战帽",
  "name_zh_tw": "戰帽",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "扩展",
  "durability": 12,
  "defense_min": 45,
  "defense_max": 53,
  "defense_avg": 49.0,
  "reqstr": 20,
  "qlvl": 34,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/cap_hat.webp"
 },
 {
  "code": "xkp",
  "name_en": "Sallet",
  "name_zh": "便盔",
  "name_zh_tw": "便盔",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "扩展",
  "durability": 18,
  "defense_min": 52,
  "defense_max": 62,
  "defense_avg": 57.0,
  "reqstr": 43,
  "qlvl": 37,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/skull_cap.webp"
 },
 {
  "code": "xlm",
  "name_en": "Casque",
  "name_zh": "兜盔",
  "name_zh_tw": "兜盔",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "扩展",
  "durability": 24,
  "defense_min": 63,
  "defense_max": 72,
  "defense_avg": 67.5,
  "reqstr": 59,
  "qlvl": 42,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/helm.webp"
 },
 {
  "code": "xhl",
  "name_en": "Basinet",
  "name_zh": "轻盔",
  "name_zh_tw": "輕盔",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "扩展",
  "durability": 30,
  "defense_min": 75,
  "defense_max": 84,
  "defense_avg": 79.5,
  "reqstr": 82,
  "qlvl": 45,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/full_helm.webp"
 },
 {
  "code": "xhm",
  "name_en": "Winged Helm",
  "name_zh": "翼盔",
  "name_zh_tw": "翼盔",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "扩展",
  "durability": 40,
  "defense_min": 85,
  "defense_max": 98,
  "defense_avg": 91.5,
  "reqstr": 115,
  "qlvl": 51,
  "max_sockets": 3,
  "sockets3": "2/2/3",
  "speed": 0,
  "img": "assets/equipment/great_helm.webp"
 },
 {
  "code": "xrn",
  "name_en": "Grand Crown",
  "name_zh": "庄严王冠",
  "name_zh_tw": "莊嚴王冠",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "扩展",
  "durability": 50,
  "defense_min": 78,
  "defense_max": 113,
  "defense_avg": 95.5,
  "reqstr": 103,
  "qlvl": 55,
  "max_sockets": 3,
  "sockets3": "2/2/3",
  "speed": 0,
  "img": "assets/equipment/crown.webp"
 },
 {
  "code": "xsk",
  "name_en": "Death Mask",
  "name_zh": "死亡面具",
  "name_zh_tw": "死亡面具",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 54,
  "defense_max": 86,
  "defense_avg": 70.0,
  "reqstr": 55,
  "qlvl": 48,
  "max_sockets": 3,
  "sockets3": "2/2/3",
  "speed": 0,
  "img": "assets/equipment/mask.webp"
 },
 {
  "code": "xui",
  "name_en": "Ghost Armor",
  "name_zh": "鬼魂战衣",
  "name_zh_tw": "鬼魂戰衣",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 102,
  "defense_max": 117,
  "defense_avg": 109.5,
  "reqstr": 38,
  "qlvl": 34,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/quilted_armor.webp"
 },
 {
  "code": "xea",
  "name_en": "Serpentskin Armor",
  "name_zh": "海蛇皮甲",
  "name_zh_tw": "海蛇皮甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 24,
  "defense_min": 111,
  "defense_max": 126,
  "defense_avg": 118.5,
  "reqstr": 43,
  "qlvl": 36,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/leather_armor.webp"
 },
 {
  "code": "xla",
  "name_en": "Demonhide Armor",
  "name_zh": "魔皮护甲",
  "name_zh_tw": "魔皮護甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 28,
  "defense_min": 122,
  "defense_max": 136,
  "defense_avg": 129.0,
  "reqstr": 50,
  "qlvl": 37,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/hard_leather_armor.webp"
 },
 {
  "code": "xtu",
  "name_en": "Trellised Armor",
  "name_zh": "格网护甲",
  "name_zh_tw": "格網護甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 32,
  "defense_min": 138,
  "defense_max": 153,
  "defense_avg": 145.5,
  "reqstr": 61,
  "qlvl": 40,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/studded_leather.webp"
 },
 {
  "code": "xng",
  "name_en": "Linked Mail",
  "name_zh": "炼扣战甲",
  "name_zh_tw": "鍊扣戰甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 26,
  "defense_min": 158,
  "defense_max": 172,
  "defense_avg": 165.0,
  "reqstr": 74,
  "qlvl": 42,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 5,
  "img": "assets/equipment/ring_mail.webp"
 },
 {
  "code": "xcl",
  "name_en": "Tigulated Mail",
  "name_zh": "锁鳞战甲",
  "name_zh_tw": "鎖鱗戰甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 36,
  "defense_min": 176,
  "defense_max": 190,
  "defense_avg": 183.0,
  "reqstr": 86,
  "qlvl": 43,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 10,
  "img": "assets/equipment/scale_mail.webp"
 },
 {
  "code": "xhn",
  "name_en": "Mesh Armor",
  "name_zh": "铁网战甲",
  "name_zh_tw": "鐵網戰甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 45,
  "defense_min": 198,
  "defense_max": 213,
  "defense_avg": 205.5,
  "reqstr": 92,
  "qlvl": 45,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 5,
  "img": "assets/equipment/chain_mail.webp"
 },
 {
  "code": "xrs",
  "name_en": "Cuirass",
  "name_zh": "护胸甲",
  "name_zh_tw": "護胸甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 50,
  "defense_min": 188,
  "defense_max": 202,
  "defense_avg": 195.0,
  "reqstr": 65,
  "qlvl": 47,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 0,
  "img": "assets/equipment/breast_plate.webp"
 },
 {
  "code": "xpl",
  "name_en": "Russet Armor",
  "name_zh": "赤褐战甲",
  "name_zh_tw": "赤褐戰甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 30,
  "defense_min": 225,
  "defense_max": 243,
  "defense_avg": 234.0,
  "reqstr": 97,
  "qlvl": 49,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 5,
  "img": "assets/equipment/splint_mail.webp"
 },
 {
  "code": "xlt",
  "name_en": "Templar Coat",
  "name_zh": "圣堂骑士战甲",
  "name_zh_tw": "聖堂騎士戰甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 60,
  "defense_min": 252,
  "defense_max": 274,
  "defense_avg": 263.0,
  "reqstr": 118,
  "qlvl": 52,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 10,
  "img": "assets/equipment/plate_mail.webp"
 },
 {
  "code": "xld",
  "name_en": "Sharktooth Armor",
  "name_zh": "鲨齿战甲",
  "name_zh_tw": "鯊齒戰甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 48,
  "defense_min": 242,
  "defense_max": 258,
  "defense_avg": 250.0,
  "reqstr": 103,
  "qlvl": 55,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 5,
  "img": "assets/equipment/field_plate.webp"
 },
 {
  "code": "xth",
  "name_en": "Embossed Plate",
  "name_zh": "雕纹战甲",
  "name_zh_tw": "雕紋戰甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 55,
  "defense_min": 282,
  "defense_max": 303,
  "defense_avg": 292.5,
  "reqstr": 125,
  "qlvl": 58,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 5,
  "img": "assets/equipment/gothic_plate.webp"
 },
 {
  "code": "xul",
  "name_en": "Chaos Armor",
  "name_zh": "混沌战甲",
  "name_zh_tw": "混沌戰甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 70,
  "defense_min": 315,
  "defense_max": 342,
  "defense_avg": 328.5,
  "reqstr": 140,
  "qlvl": 61,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 10,
  "img": "assets/equipment/full_plate_mail.webp"
 },
 {
  "code": "xar",
  "name_en": "Ornate Armor",
  "name_zh": "华丽战甲",
  "name_zh_tw": "華麗戰甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 60,
  "defense_min": 417,
  "defense_max": 450,
  "defense_avg": 433.5,
  "reqstr": 170,
  "qlvl": 64,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 5,
  "img": "assets/equipment/ancient_armor.webp"
 },
 {
  "code": "xtp",
  "name_en": "Mage Plate",
  "name_zh": "法师铠甲",
  "name_zh_tw": "法師鎧甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "扩展",
  "durability": 60,
  "defense_min": 225,
  "defense_max": 261,
  "defense_avg": 243.0,
  "reqstr": 55,
  "qlvl": 60,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 0,
  "img": "assets/equipment/light_plate.webp"
 },
 {
  "code": "xuc",
  "name_en": "Defender",
  "name_zh": "防御盾",
  "name_zh_tw": "防禦盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "扩展",
  "durability": 68,
  "defense_min": 41,
  "defense_max": 49,
  "defense_avg": 45.0,
  "reqstr": 38,
  "qlvl": 34,
  "max_sockets": 1,
  "sockets3": "1/1/1",
  "speed": 0,
  "img": "assets/equipment/buckler.webp"
 },
 {
  "code": "xml",
  "name_en": "Round Shield",
  "name_zh": "圆型盾",
  "name_zh_tw": "圓型盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "扩展",
  "durability": 64,
  "defense_min": 47,
  "defense_max": 55,
  "defense_avg": 51.0,
  "reqstr": 53,
  "qlvl": 37,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/small_shield.webp"
 },
 {
  "code": "xrg",
  "name_en": "Scutum",
  "name_zh": "大圆盾",
  "name_zh_tw": "大圓盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "扩展",
  "durability": 62,
  "defense_min": 53,
  "defense_max": 61,
  "defense_avg": 57.0,
  "reqstr": 71,
  "qlvl": 42,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 5,
  "img": "assets/equipment/large_shield.webp"
 },
 {
  "code": "xit",
  "name_en": "Dragon Shield",
  "name_zh": "龙盾",
  "name_zh_tw": "龍盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "扩展",
  "durability": 76,
  "defense_min": 59,
  "defense_max": 67,
  "defense_avg": 63.0,
  "reqstr": 91,
  "qlvl": 45,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 0,
  "img": "assets/equipment/kite_shield.webp"
 },
 {
  "code": "xow",
  "name_en": "Pavise",
  "name_zh": "大盾",
  "name_zh_tw": "大盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "扩展",
  "durability": 72,
  "defense_min": 68,
  "defense_max": 78,
  "defense_avg": 73.0,
  "reqstr": 133,
  "qlvl": 50,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 10,
  "img": "assets/equipment/tower_shield.webp"
 },
 {
  "code": "xts",
  "name_en": "Ancient Shield",
  "name_zh": "上古盾",
  "name_zh_tw": "上古盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "扩展",
  "durability": 80,
  "defense_min": 80,
  "defense_max": 93,
  "defense_avg": 86.5,
  "reqstr": 110,
  "qlvl": 56,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 5,
  "img": "assets/equipment/gothic_shield.webp"
 },
 {
  "code": "xlg",
  "name_en": "Demonhide Gloves",
  "name_zh": "魔皮手套",
  "name_zh_tw": "魔皮手套",
  "category": "手套",
  "type_raw": "glov",
  "tier": "扩展",
  "durability": 12,
  "defense_min": 28,
  "defense_max": 35,
  "defense_avg": 31.5,
  "reqstr": 20,
  "qlvl": 33,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/gloves_l.webp"
 },
 {
  "code": "xvg",
  "name_en": "Sharkskin Gloves",
  "name_zh": "鲨皮手套",
  "name_zh_tw": "鯊皮手套",
  "category": "手套",
  "type_raw": "glov",
  "tier": "扩展",
  "durability": 14,
  "defense_min": 33,
  "defense_max": 39,
  "defense_avg": 36.0,
  "reqstr": 20,
  "qlvl": 39,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/heavy_gloves.webp"
 },
 {
  "code": "xmg",
  "name_en": "Heavy Bracers",
  "name_zh": "重型护腕",
  "name_zh_tw": "重型護腕",
  "category": "手套",
  "type_raw": "glov",
  "tier": "扩展",
  "durability": 16,
  "defense_min": 37,
  "defense_max": 44,
  "defense_avg": 40.5,
  "reqstr": 58,
  "qlvl": 43,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/bracers_m.webp"
 },
 {
  "code": "xtg",
  "name_en": "Battle Gauntlets",
  "name_zh": "战斗护手",
  "name_zh_tw": "戰鬥護手",
  "category": "手套",
  "type_raw": "glov",
  "tier": "扩展",
  "durability": 18,
  "defense_min": 39,
  "defense_max": 47,
  "defense_avg": 43.0,
  "reqstr": 88,
  "qlvl": 49,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/light_gauntlets.webp"
 },
 {
  "code": "xhg",
  "name_en": "War Gauntlets",
  "name_zh": "征战护手",
  "name_zh_tw": "征戰護手",
  "category": "手套",
  "type_raw": "glov",
  "tier": "扩展",
  "durability": 24,
  "defense_min": 43,
  "defense_max": 53,
  "defense_avg": 48.0,
  "reqstr": 110,
  "qlvl": 54,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/gaunlets_h.webp"
 },
 {
  "code": "xlb",
  "name_en": "Demonhide Boots",
  "name_zh": "魔皮长靴",
  "name_zh_tw": "魔皮長靴",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "扩展",
  "durability": 12,
  "defense_min": 28,
  "defense_max": 35,
  "defense_avg": 31.5,
  "reqstr": 20,
  "qlvl": 36,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/leather_boots.webp"
 },
 {
  "code": "xvb",
  "name_en": "Sharkskin Boots",
  "name_zh": "鲨皮靴",
  "name_zh_tw": "鯊皮靴",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "扩展",
  "durability": 14,
  "defense_min": 33,
  "defense_max": 39,
  "defense_avg": 36.0,
  "reqstr": 47,
  "qlvl": 39,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/heavy_boots.webp"
 },
 {
  "code": "xmb",
  "name_en": "Mesh Boots",
  "name_zh": "铁网靴",
  "name_zh_tw": "鐵網靴",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "扩展",
  "durability": 16,
  "defense_min": 37,
  "defense_max": 44,
  "defense_avg": 40.5,
  "reqstr": 65,
  "qlvl": 43,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/chain_boots.webp"
 },
 {
  "code": "xtb",
  "name_en": "Battle Boots",
  "name_zh": "战斗靴",
  "name_zh_tw": "戰鬥靴",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "扩展",
  "durability": 18,
  "defense_min": 39,
  "defense_max": 47,
  "defense_avg": 43.0,
  "reqstr": 95,
  "qlvl": 49,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/light_plate_boots.webp"
 },
 {
  "code": "xhb",
  "name_en": "War Boots",
  "name_zh": "征战靴",
  "name_zh_tw": "征戰靴",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "扩展",
  "durability": 24,
  "defense_min": 43,
  "defense_max": 53,
  "defense_avg": 48.0,
  "reqstr": 125,
  "qlvl": 54,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/plate_boots.webp"
 },
 {
  "code": "zlb",
  "name_en": "Demonhide Sash",
  "name_zh": "魔皮束带",
  "name_zh_tw": "魔皮束帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "扩展",
  "durability": 12,
  "defense_min": 29,
  "defense_max": 34,
  "defense_avg": 31.5,
  "reqstr": 20,
  "qlvl": 36,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/sash_l.webp"
 },
 {
  "code": "zvb",
  "name_en": "Sharkskin Belt",
  "name_zh": "鲨皮腰带",
  "name_zh_tw": "鯊皮腰帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "扩展",
  "durability": 14,
  "defense_min": 31,
  "defense_max": 36,
  "defense_avg": 33.5,
  "reqstr": 20,
  "qlvl": 39,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/light_belt.webp"
 },
 {
  "code": "zmb",
  "name_en": "Mesh Belt",
  "name_zh": "铁网腰带",
  "name_zh_tw": "鐵網腰帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "扩展",
  "durability": 16,
  "defense_min": 35,
  "defense_max": 40,
  "defense_avg": 37.5,
  "reqstr": 58,
  "qlvl": 43,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/belt_m.webp"
 },
 {
  "code": "ztb",
  "name_en": "Battle Belt",
  "name_zh": "战斗腰带",
  "name_zh_tw": "戰鬥腰帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "扩展",
  "durability": 18,
  "defense_min": 37,
  "defense_max": 42,
  "defense_avg": 39.5,
  "reqstr": 88,
  "qlvl": 49,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/heavy_belt.webp"
 },
 {
  "code": "zhb",
  "name_en": "War Belt",
  "name_zh": "征战腰带",
  "name_zh_tw": "征戰腰帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "扩展",
  "durability": 24,
  "defense_min": 41,
  "defense_max": 52,
  "defense_avg": 46.5,
  "reqstr": 110,
  "qlvl": 54,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/girdle_h.webp"
 },
 {
  "code": "xh9",
  "name_en": "Grim Helm",
  "name_zh": "阴森头盔",
  "name_zh_tw": "陰森頭盔",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "扩展",
  "durability": 40,
  "defense_min": 60,
  "defense_max": 125,
  "defense_avg": 92.5,
  "reqstr": 58,
  "qlvl": 50,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/bone_helm.webp"
 },
 {
  "code": "xsh",
  "name_en": "Grim Shield",
  "name_zh": "阴森盾牌",
  "name_zh_tw": "陰森盾牌",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "扩展",
  "durability": 70,
  "defense_min": 50,
  "defense_max": 150,
  "defense_avg": 100.0,
  "reqstr": 58,
  "qlvl": 48,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/bone_shield.webp"
 },
 {
  "code": "xpk",
  "name_en": "Barbed Shield",
  "name_zh": "倒刺盾",
  "name_zh_tw": "倒刺盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "扩展",
  "durability": 55,
  "defense_min": 58,
  "defense_max": 78,
  "defense_avg": 68.0,
  "reqstr": 65,
  "qlvl": 42,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/spiked_shield.webp"
 },
 {
  "code": "dr1",
  "name_en": "Wolf Head",
  "name_zh": "狼头兽帽",
  "name_zh_tw": "狼頭獸帽",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "普通",
  "durability": 20,
  "defense_min": 8,
  "defense_max": 11,
  "defense_avg": 9.5,
  "reqstr": 16,
  "qlvl": 4,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/wolf_head.webp"
 },
 {
  "code": "dr2",
  "name_en": "Hawk Helm",
  "name_zh": "飞鹰头盔",
  "name_zh_tw": "飛鷹頭盔",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "普通",
  "durability": 20,
  "defense_min": 4,
  "defense_max": 15,
  "defense_avg": 9.5,
  "reqstr": 20,
  "qlvl": 8,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/hawk_helm.webp"
 },
 {
  "code": "dr3",
  "name_en": "Antlers",
  "name_zh": "巨角兽帽",
  "name_zh_tw": "巨角獸帽",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "普通",
  "durability": 20,
  "defense_min": 18,
  "defense_max": 24,
  "defense_avg": 21.0,
  "reqstr": 24,
  "qlvl": 16,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/antlers.webp"
 },
 {
  "code": "dr4",
  "name_en": "Falcon Mask",
  "name_zh": "猎鹰面具",
  "name_zh_tw": "獵鷹面具",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "普通",
  "durability": 20,
  "defense_min": 12,
  "defense_max": 28,
  "defense_avg": 20.0,
  "reqstr": 28,
  "qlvl": 20,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/falcon_mask.webp"
 },
 {
  "code": "dr5",
  "name_en": "Spirit Mask",
  "name_zh": "灵狼面具",
  "name_zh_tw": "靈狼面具",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "普通",
  "durability": 20,
  "defense_min": 22,
  "defense_max": 35,
  "defense_avg": 28.5,
  "reqstr": 30,
  "qlvl": 24,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/spirit_mask.webp"
 },
 {
  "code": "ba1",
  "name_en": "Jawbone Cap",
  "name_zh": "颚骨帽",
  "name_zh_tw": "顎骨帽",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "普通",
  "durability": 25,
  "defense_min": 10,
  "defense_max": 15,
  "defense_avg": 12.5,
  "reqstr": 25,
  "qlvl": 4,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/jawbone_cap.webp"
 },
 {
  "code": "ba2",
  "name_en": "Fanged Helm",
  "name_zh": "尖牙头盔",
  "name_zh_tw": "尖牙頭盔",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "普通",
  "durability": 35,
  "defense_min": 15,
  "defense_max": 20,
  "defense_avg": 17.5,
  "reqstr": 35,
  "qlvl": 8,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/fanged_helm.webp"
 },
 {
  "code": "ba3",
  "name_en": "Horned Helm",
  "name_zh": "尖角头盔",
  "name_zh_tw": "尖角頭盔",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "普通",
  "durability": 45,
  "defense_min": 25,
  "defense_max": 30,
  "defense_avg": 27.5,
  "reqstr": 45,
  "qlvl": 16,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/horned_helm.webp"
 },
 {
  "code": "ba4",
  "name_en": "Assault Helmet",
  "name_zh": "突击头盔",
  "name_zh_tw": "突擊頭盔",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "普通",
  "durability": 50,
  "defense_min": 30,
  "defense_max": 35,
  "defense_avg": 32.5,
  "reqstr": 55,
  "qlvl": 20,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/assault_helmet.webp"
 },
 {
  "code": "ba5",
  "name_en": "Avenger Guard",
  "name_zh": "复仇者护盔",
  "name_zh_tw": "復仇者護盔",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "普通",
  "durability": 55,
  "defense_min": 35,
  "defense_max": 50,
  "defense_avg": 42.5,
  "reqstr": 65,
  "qlvl": 24,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/avenger_guard.webp"
 },
 {
  "code": "pa1",
  "name_en": "Targe",
  "name_zh": "小盾",
  "name_zh_tw": "小盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "普通",
  "durability": 20,
  "defense_min": 8,
  "defense_max": 12,
  "defense_avg": 10.0,
  "reqstr": 16,
  "qlvl": 4,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/targe.webp"
 },
 {
  "code": "pa2",
  "name_en": "Rondache",
  "name_zh": "轻圆盾",
  "name_zh_tw": "輕圓盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "普通",
  "durability": 30,
  "defense_min": 10,
  "defense_max": 18,
  "defense_avg": 14.0,
  "reqstr": 26,
  "qlvl": 8,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/rondache.webp"
 },
 {
  "code": "pa3",
  "name_en": "Heraldic Shield",
  "name_zh": "纹章盾",
  "name_zh_tw": "紋章盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "普通",
  "durability": 40,
  "defense_min": 16,
  "defense_max": 26,
  "defense_avg": 21.0,
  "reqstr": 40,
  "qlvl": 16,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/heraldic_shield.webp"
 },
 {
  "code": "pa4",
  "name_en": "Aerin Shield",
  "name_zh": "艾文之盾",
  "name_zh_tw": "艾文之盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "普通",
  "durability": 50,
  "defense_min": 26,
  "defense_max": 36,
  "defense_avg": 31.0,
  "reqstr": 50,
  "qlvl": 20,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/aerin_shield.webp"
 },
 {
  "code": "pa5",
  "name_en": "Crown Shield",
  "name_zh": "冠冕之盾",
  "name_zh_tw": "冠冕之盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "普通",
  "durability": 60,
  "defense_min": 30,
  "defense_max": 40,
  "defense_avg": 35.0,
  "reqstr": 65,
  "qlvl": 24,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/crown_shield.webp"
 },
 {
  "code": "ne1",
  "name_en": "Preserved Head",
  "name_zh": "防腐头颅",
  "name_zh_tw": "防腐頭顱",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "普通",
  "durability": 20,
  "defense_min": 2,
  "defense_max": 5,
  "defense_avg": 3.5,
  "reqstr": 12,
  "qlvl": 4,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/preserved_head.webp"
 },
 {
  "code": "ne2",
  "name_en": "Zombie Head",
  "name_zh": "僵尸头颅",
  "name_zh_tw": "殭屍頭顱",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "普通",
  "durability": 20,
  "defense_min": 4,
  "defense_max": 8,
  "defense_avg": 6.0,
  "reqstr": 14,
  "qlvl": 8,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/zombie_head.webp"
 },
 {
  "code": "ne3",
  "name_en": "Unraveller Head",
  "name_zh": "解绷者头颅",
  "name_zh_tw": "解繃者頭顱",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "普通",
  "durability": 20,
  "defense_min": 6,
  "defense_max": 10,
  "defense_avg": 8.0,
  "reqstr": 18,
  "qlvl": 16,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/unraveller_head.webp"
 },
 {
  "code": "ne4",
  "name_en": "Gargoyle Head",
  "name_zh": "石像鬼头颅",
  "name_zh_tw": "石像鬼頭顱",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "普通",
  "durability": 20,
  "defense_min": 10,
  "defense_max": 16,
  "defense_avg": 13.0,
  "reqstr": 20,
  "qlvl": 20,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/gargoyle_head.webp"
 },
 {
  "code": "ne5",
  "name_en": "Demon Head",
  "name_zh": "恶魔头颅",
  "name_zh_tw": "惡魔頭顱",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "普通",
  "durability": 20,
  "defense_min": 15,
  "defense_max": 20,
  "defense_avg": 17.5,
  "reqstr": 25,
  "qlvl": 24,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/demon_head.webp"
 },
 {
  "code": "ci0",
  "name_en": "Circlet",
  "name_zh": "头环",
  "name_zh_tw": "頭環",
  "category": "头盔",
  "type_raw": "circ",
  "tier": "普通",
  "durability": 35,
  "defense_min": 20,
  "defense_max": 30,
  "defense_avg": 25.0,
  "reqstr": 0,
  "qlvl": 24,
  "max_sockets": 2,
  "sockets3": "1/2/2",
  "speed": 0,
  "img": "assets/equipment/circlet.webp"
 },
 {
  "code": "ci1",
  "name_en": "Coronet",
  "name_zh": "宝冠",
  "name_zh_tw": "寶冠",
  "category": "头盔",
  "type_raw": "circ",
  "tier": "普通",
  "durability": 30,
  "defense_min": 30,
  "defense_max": 40,
  "defense_avg": 35.0,
  "reqstr": 0,
  "qlvl": 52,
  "max_sockets": 2,
  "sockets3": "1/2/2",
  "speed": 0,
  "img": "assets/equipment/coronet.webp"
 },
 {
  "code": "ci2",
  "name_en": "Tiara",
  "name_zh": "头冠",
  "name_zh_tw": "頭冠",
  "category": "头盔",
  "type_raw": "circ",
  "tier": "扩展",
  "durability": 25,
  "defense_min": 40,
  "defense_max": 50,
  "defense_avg": 45.0,
  "reqstr": 0,
  "qlvl": 70,
  "max_sockets": 3,
  "sockets3": "1/2/3",
  "speed": 0,
  "img": "assets/equipment/tiara.webp"
 },
 {
  "code": "ci3",
  "name_en": "Diadem",
  "name_zh": "权冠",
  "name_zh_tw": "權冠",
  "category": "头盔",
  "type_raw": "circ",
  "tier": "精英",
  "durability": 20,
  "defense_min": 50,
  "defense_max": 60,
  "defense_avg": 55.0,
  "reqstr": 0,
  "qlvl": 85,
  "max_sockets": 3,
  "sockets3": "1/2/3",
  "speed": 0,
  "img": "assets/equipment/diadem.webp"
 },
 {
  "code": "uap",
  "name_en": "Shako",
  "name_zh": "军帽",
  "name_zh_tw": "軍帽",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "精英",
  "durability": 12,
  "defense_min": 98,
  "defense_max": 141,
  "defense_avg": 119.5,
  "reqstr": 50,
  "qlvl": 58,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/cap_hat.webp"
 },
 {
  "code": "ukp",
  "name_en": "Hydraskull",
  "name_zh": "多头蛇颅盔",
  "name_zh_tw": "多頭蛇顱盔",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "精英",
  "durability": 18,
  "defense_min": 101,
  "defense_max": 145,
  "defense_avg": 123.0,
  "reqstr": 84,
  "qlvl": 63,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/skull_cap.webp"
 },
 {
  "code": "ulm",
  "name_en": "Armet",
  "name_zh": "覆颊盔",
  "name_zh_tw": "覆頰盔",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "精英",
  "durability": 24,
  "defense_min": 105,
  "defense_max": 149,
  "defense_avg": 127.0,
  "reqstr": 109,
  "qlvl": 68,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/helm.webp"
 },
 {
  "code": "uhl",
  "name_en": "Giant Conch",
  "name_zh": "巨螺盔",
  "name_zh_tw": "巨螺盔",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "精英",
  "durability": 30,
  "defense_min": 110,
  "defense_max": 154,
  "defense_avg": 132.0,
  "reqstr": 142,
  "qlvl": 54,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/full_helm.webp"
 },
 {
  "code": "uhm",
  "name_en": "Spired Helm",
  "name_zh": "巨角头盔",
  "name_zh_tw": "巨角頭盔",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "精英",
  "durability": 40,
  "defense_min": 114,
  "defense_max": 159,
  "defense_avg": 136.5,
  "reqstr": 192,
  "qlvl": 79,
  "max_sockets": 3,
  "sockets3": "2/2/3",
  "speed": 0,
  "img": "assets/equipment/great_helm.webp"
 },
 {
  "code": "urn",
  "name_en": "Corona",
  "name_zh": "日冕之冠",
  "name_zh_tw": "日冕之冠",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "精英",
  "durability": 50,
  "defense_min": 111,
  "defense_max": 165,
  "defense_avg": 138.0,
  "reqstr": 174,
  "qlvl": 85,
  "max_sockets": 3,
  "sockets3": "2/2/3",
  "speed": 0,
  "img": "assets/equipment/crown.webp"
 },
 {
  "code": "usk",
  "name_en": "Demonhead",
  "name_zh": "恶魔头骨",
  "name_zh_tw": "惡魔頭骨",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "精英",
  "durability": 20,
  "defense_min": 101,
  "defense_max": 154,
  "defense_avg": 127.5,
  "reqstr": 102,
  "qlvl": 74,
  "max_sockets": 3,
  "sockets3": "2/2/3",
  "speed": 0,
  "img": "assets/equipment/mask.webp"
 },
 {
  "code": "uui",
  "name_en": "Dusk Shroud",
  "name_zh": "灰暮罩衣",
  "name_zh_tw": "灰暮罩衣",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 20,
  "defense_min": 361,
  "defense_max": 467,
  "defense_avg": 414.0,
  "reqstr": 77,
  "qlvl": 65,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/quilted_armor.webp"
 },
 {
  "code": "uea",
  "name_en": "Wyrmhide",
  "name_zh": "龙皮甲",
  "name_zh_tw": "龍皮甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 24,
  "defense_min": 364,
  "defense_max": 470,
  "defense_avg": 417.0,
  "reqstr": 84,
  "qlvl": 67,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/leather_armor.webp"
 },
 {
  "code": "ula",
  "name_en": "Scarab Husk",
  "name_zh": "圣甲虫壳皮甲",
  "name_zh_tw": "聖甲蟲殼皮甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 28,
  "defense_min": 369,
  "defense_max": 474,
  "defense_avg": 421.5,
  "reqstr": 95,
  "qlvl": 68,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/hard_leather_armor.webp"
 },
 {
  "code": "utu",
  "name_en": "Wire Fleece",
  "name_zh": "钢线毛皮甲",
  "name_zh_tw": "鋼線毛皮甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 32,
  "defense_min": 375,
  "defense_max": 481,
  "defense_avg": 428.0,
  "reqstr": 111,
  "qlvl": 70,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/studded_leather.webp"
 },
 {
  "code": "ung",
  "name_en": "Diamond Mail",
  "name_zh": "钻石锁甲",
  "name_zh_tw": "鑽石鎖甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 26,
  "defense_min": 383,
  "defense_max": 489,
  "defense_avg": 436.0,
  "reqstr": 131,
  "qlvl": 72,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 5,
  "img": "assets/equipment/ring_mail.webp"
 },
 {
  "code": "ucl",
  "name_en": "Loricated Mail",
  "name_zh": "缀鳞战甲",
  "name_zh_tw": "綴鱗戰甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 36,
  "defense_min": 390,
  "defense_max": 496,
  "defense_avg": 443.0,
  "reqstr": 149,
  "qlvl": 73,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 10,
  "img": "assets/equipment/scale_mail.webp"
 },
 {
  "code": "uhn",
  "name_en": "Boneweave",
  "name_zh": "骸骨网甲",
  "name_zh_tw": "骸骨網甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 45,
  "defense_min": 399,
  "defense_max": 505,
  "defense_avg": 452.0,
  "reqstr": 158,
  "qlvl": 62,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 5,
  "img": "assets/equipment/chain_mail.webp"
 },
 {
  "code": "urs",
  "name_en": "Great Hauberk",
  "name_zh": "鳞铠胸甲",
  "name_zh_tw": "鱗鎧胸甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 50,
  "defense_min": 395,
  "defense_max": 501,
  "defense_avg": 448.0,
  "reqstr": 118,
  "qlvl": 75,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/breast_plate.webp"
 },
 {
  "code": "upl",
  "name_en": "Balrog Skin",
  "name_zh": "炎魔皮板甲",
  "name_zh_tw": "炎魔皮板甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 30,
  "defense_min": 410,
  "defense_max": 517,
  "defense_avg": 463.5,
  "reqstr": 165,
  "qlvl": 76,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 5,
  "img": "assets/equipment/splint_mail.webp"
 },
 {
  "code": "ult",
  "name_en": "Hellforge Plate",
  "name_zh": "地狱锻甲",
  "name_zh_tw": "地獄鍛甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 60,
  "defense_min": 421,
  "defense_max": 530,
  "defense_avg": 475.5,
  "reqstr": 196,
  "qlvl": 78,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 10,
  "img": "assets/equipment/plate_mail.webp"
 },
 {
  "code": "uld",
  "name_en": "Kraken Shell",
  "name_zh": "海怪之壳",
  "name_zh_tw": "海怪之殼",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 48,
  "defense_min": 417,
  "defense_max": 523,
  "defense_avg": 470.0,
  "reqstr": 174,
  "qlvl": 81,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 5,
  "img": "assets/equipment/field_plate.webp"
 },
 {
  "code": "uth",
  "name_en": "Lacquered Plate",
  "name_zh": "漆护铠甲",
  "name_zh_tw": "漆護鎧甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 55,
  "defense_min": 433,
  "defense_max": 541,
  "defense_avg": 487.0,
  "reqstr": 208,
  "qlvl": 82,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 5,
  "img": "assets/equipment/gothic_plate.webp"
 },
 {
  "code": "uul",
  "name_en": "Shadow Plate",
  "name_zh": "暗影铠甲",
  "name_zh_tw": "暗影鎧甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 70,
  "defense_min": 446,
  "defense_max": 557,
  "defense_avg": 501.5,
  "reqstr": 230,
  "qlvl": 83,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 10,
  "img": "assets/equipment/full_plate_mail.webp"
 },
 {
  "code": "uar",
  "name_en": "Sacred Armor",
  "name_zh": "神圣战甲",
  "name_zh_tw": "神聖戰甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 60,
  "defense_min": 487,
  "defense_max": 600,
  "defense_avg": 543.5,
  "reqstr": 232,
  "qlvl": 85,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 5,
  "img": "assets/equipment/ancient_armor.webp"
 },
 {
  "code": "utp",
  "name_en": "Archon Plate",
  "name_zh": "统御者铠甲",
  "name_zh_tw": "統御者鎧甲",
  "category": "铠甲",
  "type_raw": "tors",
  "tier": "精英",
  "durability": 60,
  "defense_min": 410,
  "defense_max": 524,
  "defense_avg": 467.0,
  "reqstr": 103,
  "qlvl": 84,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/light_plate.webp"
 },
 {
  "code": "uuc",
  "name_en": "Heater",
  "name_zh": "斗盾",
  "name_zh_tw": "斗盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "精英",
  "durability": 88,
  "defense_min": 95,
  "defense_max": 110,
  "defense_avg": 102.5,
  "reqstr": 77,
  "qlvl": 58,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/buckler.webp"
 },
 {
  "code": "uml",
  "name_en": "Luna",
  "name_zh": "圆月盾",
  "name_zh_tw": "圓月盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "精英",
  "durability": 84,
  "defense_min": 108,
  "defense_max": 123,
  "defense_avg": 115.5,
  "reqstr": 100,
  "qlvl": 61,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/small_shield.webp"
 },
 {
  "code": "urg",
  "name_en": "Hyperion",
  "name_zh": "亥伯龙盾",
  "name_zh_tw": "亥伯龍盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "精英",
  "durability": 82,
  "defense_min": 119,
  "defense_max": 135,
  "defense_avg": 127.0,
  "reqstr": 127,
  "qlvl": 64,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 5,
  "img": "assets/equipment/large_shield.webp"
 },
 {
  "code": "uit",
  "name_en": "Monarch",
  "name_zh": "君主盾",
  "name_zh_tw": "君主盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "精英",
  "durability": 86,
  "defense_min": 133,
  "defense_max": 148,
  "defense_avg": 140.5,
  "reqstr": 156,
  "qlvl": 72,
  "max_sockets": 4,
  "sockets3": "3/3/4",
  "speed": 0,
  "img": "assets/equipment/kite_shield.webp"
 },
 {
  "code": "uow",
  "name_en": "Aegis",
  "name_zh": "御塔盾",
  "name_zh_tw": "禦塔盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "精英",
  "durability": 92,
  "defense_min": 145,
  "defense_max": 161,
  "defense_avg": 153.0,
  "reqstr": 219,
  "qlvl": 79,
  "max_sockets": 4,
  "sockets3": "3/3/4",
  "speed": 10,
  "img": "assets/equipment/tower_shield.webp"
 },
 {
  "code": "uts",
  "name_en": "Ward",
  "name_zh": "庇护盾",
  "name_zh_tw": "庇護盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "精英",
  "durability": 100,
  "defense_min": 153,
  "defense_max": 170,
  "defense_avg": 161.5,
  "reqstr": 185,
  "qlvl": 84,
  "max_sockets": 4,
  "sockets3": "3/3/4",
  "speed": 5,
  "img": "assets/equipment/gothic_shield.webp"
 },
 {
  "code": "ulg",
  "name_en": "Bramble Mitts",
  "name_zh": "荆棘手套",
  "name_zh_tw": "荊棘手套",
  "category": "手套",
  "type_raw": "glov",
  "tier": "精英",
  "durability": 12,
  "defense_min": 54,
  "defense_max": 62,
  "defense_avg": 58.0,
  "reqstr": 50,
  "qlvl": 57,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/gloves_l.webp"
 },
 {
  "code": "uvg",
  "name_en": "Vampirebone Gloves",
  "name_zh": "吸血鬼骸骨手套",
  "name_zh_tw": "吸血鬼骸骨手套",
  "category": "手套",
  "type_raw": "glov",
  "tier": "精英",
  "durability": 14,
  "defense_min": 56,
  "defense_max": 65,
  "defense_avg": 60.5,
  "reqstr": 50,
  "qlvl": 63,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/heavy_gloves.webp"
 },
 {
  "code": "umg",
  "name_en": "Vambraces",
  "name_zh": "护臂",
  "name_zh_tw": "護臂",
  "category": "手套",
  "type_raw": "glov",
  "tier": "精英",
  "durability": 16,
  "defense_min": 59,
  "defense_max": 67,
  "defense_avg": 63.0,
  "reqstr": 106,
  "qlvl": 69,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/bracers_m.webp"
 },
 {
  "code": "utg",
  "name_en": "Crusader Gauntlets",
  "name_zh": "圣教军护手",
  "name_zh_tw": "聖教軍護手",
  "category": "手套",
  "type_raw": "glov",
  "tier": "精英",
  "durability": 18,
  "defense_min": 59,
  "defense_max": 68,
  "defense_avg": 63.5,
  "reqstr": 151,
  "qlvl": 76,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/light_gauntlets.webp"
 },
 {
  "code": "uhg",
  "name_en": "Ogre Gauntlets",
  "name_zh": "巨魔护手",
  "name_zh_tw": "巨魔護手",
  "category": "手套",
  "type_raw": "glov",
  "tier": "精英",
  "durability": 24,
  "defense_min": 62,
  "defense_max": 71,
  "defense_avg": 66.5,
  "reqstr": 185,
  "qlvl": 85,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/gaunlets_h.webp"
 },
 {
  "code": "ulb",
  "name_en": "Wyrmhide Boots",
  "name_zh": "龙皮靴",
  "name_zh_tw": "龍皮靴",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "精英",
  "durability": 12,
  "defense_min": 54,
  "defense_max": 62,
  "defense_avg": 58.0,
  "reqstr": 50,
  "qlvl": 60,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/leather_boots.webp"
 },
 {
  "code": "uvb",
  "name_en": "Scarabshell Boots",
  "name_zh": "圣甲虫壳皮靴",
  "name_zh_tw": "聖甲蟲殼皮靴",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "精英",
  "durability": 14,
  "defense_min": 56,
  "defense_max": 65,
  "defense_avg": 60.5,
  "reqstr": 91,
  "qlvl": 66,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/heavy_boots.webp"
 },
 {
  "code": "umb",
  "name_en": "Boneweave Boots",
  "name_zh": "骸骨网靴",
  "name_zh_tw": "骸骨網靴",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "精英",
  "durability": 16,
  "defense_min": 59,
  "defense_max": 67,
  "defense_avg": 63.0,
  "reqstr": 118,
  "qlvl": 72,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/chain_boots.webp"
 },
 {
  "code": "utb",
  "name_en": "Mirrored Boots",
  "name_zh": "幻镜战靴",
  "name_zh_tw": "幻鏡戰靴",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "精英",
  "durability": 18,
  "defense_min": 59,
  "defense_max": 68,
  "defense_avg": 63.5,
  "reqstr": 163,
  "qlvl": 81,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/light_plate_boots.webp"
 },
 {
  "code": "uhb",
  "name_en": "Myrmidon Greaves",
  "name_zh": "勇士护胫",
  "name_zh_tw": "勇士護脛",
  "category": "靴子",
  "type_raw": "boot",
  "tier": "精英",
  "durability": 24,
  "defense_min": 62,
  "defense_max": 71,
  "defense_avg": 66.5,
  "reqstr": 208,
  "qlvl": 85,
  "max_sockets": 4,
  "sockets3": "1/2/4",
  "speed": 0,
  "img": "assets/equipment/plate_boots.webp"
 },
 {
  "code": "ulc",
  "name_en": "Spiderweb Sash",
  "name_zh": "蛛网束带",
  "name_zh_tw": "蛛網束帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "精英",
  "durability": 12,
  "defense_min": 55,
  "defense_max": 62,
  "defense_avg": 58.5,
  "reqstr": 50,
  "qlvl": 61,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/sash_l.webp"
 },
 {
  "code": "uvc",
  "name_en": "Vampirefang Belt",
  "name_zh": "吸血鬼牙腰带",
  "name_zh_tw": "吸血鬼牙腰帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "精英",
  "durability": 14,
  "defense_min": 56,
  "defense_max": 63,
  "defense_avg": 59.5,
  "reqstr": 50,
  "qlvl": 68,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/light_belt.webp"
 },
 {
  "code": "umc",
  "name_en": "Mithril Coil",
  "name_zh": "秘银腰带",
  "name_zh_tw": "秘銀腰帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "精英",
  "durability": 16,
  "defense_min": 58,
  "defense_max": 65,
  "defense_avg": 61.5,
  "reqstr": 106,
  "qlvl": 75,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/belt_m.webp"
 },
 {
  "code": "utc",
  "name_en": "Troll Belt",
  "name_zh": "食人妖腰带",
  "name_zh_tw": "食人妖腰帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "精英",
  "durability": 18,
  "defense_min": 59,
  "defense_max": 66,
  "defense_avg": 62.5,
  "reqstr": 151,
  "qlvl": 82,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/heavy_belt.webp"
 },
 {
  "code": "uhc",
  "name_en": "Colossus Girdle",
  "name_zh": "巨神腰带",
  "name_zh_tw": "巨神腰帶",
  "category": "腰带",
  "type_raw": "belt",
  "tier": "精英",
  "durability": 24,
  "defense_min": 61,
  "defense_max": 71,
  "defense_avg": 66.0,
  "reqstr": 185,
  "qlvl": 85,
  "max_sockets": 2,
  "sockets3": "1/1/2",
  "speed": 0,
  "img": "assets/equipment/girdle_h.webp"
 },
 {
  "code": "uh9",
  "name_en": "Bone Visage",
  "name_zh": "骸骨面罩",
  "name_zh_tw": "骸骨面罩",
  "category": "头盔",
  "type_raw": "helm",
  "tier": "精英",
  "durability": 40,
  "defense_min": 100,
  "defense_max": 157,
  "defense_avg": 128.5,
  "reqstr": 106,
  "qlvl": 84,
  "max_sockets": 3,
  "sockets3": "2/2/3",
  "speed": 0,
  "img": "assets/equipment/bone_helm.webp"
 },
 {
  "code": "ush",
  "name_en": "Troll Nest",
  "name_zh": "食人妖骨盾",
  "name_zh_tw": "食人妖骨盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "精英",
  "durability": 74,
  "defense_min": 158,
  "defense_max": 173,
  "defense_avg": 165.5,
  "reqstr": 106,
  "qlvl": 76,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 0,
  "img": "assets/equipment/bone_shield.webp"
 },
 {
  "code": "upk",
  "name_en": "Blade Barrier",
  "name_zh": "刀刃刺盾",
  "name_zh_tw": "刀刃刺盾",
  "category": "盾牌",
  "type_raw": "shie",
  "tier": "精英",
  "durability": 83,
  "defense_min": 147,
  "defense_max": 163,
  "defense_avg": 155.0,
  "reqstr": 118,
  "qlvl": 68,
  "max_sockets": 3,
  "sockets3": "3/3/3",
  "speed": 0,
  "img": "assets/equipment/spiked_shield.webp"
 },
 {
  "code": "dr6",
  "name_en": "Alpha Helm",
  "name_zh": "猛狼头盔",
  "name_zh_tw": "猛狼頭盔",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 52,
  "defense_max": 62,
  "defense_avg": 57.0,
  "reqstr": 44,
  "qlvl": 35,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/wolf_head.webp"
 },
 {
  "code": "dr7",
  "name_en": "Griffon Headress",
  "name_zh": "狮鹫兽头饰",
  "name_zh_tw": "獅鷲獸頭飾",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 46,
  "defense_max": 68,
  "defense_avg": 57.0,
  "reqstr": 50,
  "qlvl": 40,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/hawk_helm.webp"
 },
 {
  "code": "dr8",
  "name_en": "Hunter's Guise",
  "name_zh": "猎人面罩",
  "name_zh_tw": "獵人面罩",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 67,
  "defense_max": 81,
  "defense_avg": 74.0,
  "reqstr": 56,
  "qlvl": 46,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/antlers.webp"
 },
 {
  "code": "dr9",
  "name_en": "Sacred Feathers",
  "name_zh": "圣羽头饰",
  "name_zh_tw": "聖羽頭飾",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 58,
  "defense_max": 87,
  "defense_avg": 72.5,
  "reqstr": 62,
  "qlvl": 50,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/falcon_mask.webp"
 },
 {
  "code": "dra",
  "name_en": "Totemic Mask",
  "name_zh": "图腾面具",
  "name_zh_tw": "圖騰面具",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 73,
  "defense_max": 98,
  "defense_avg": 85.5,
  "reqstr": 65,
  "qlvl": 55,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/spirit_mask.webp"
 },
 {
  "code": "ba6",
  "name_en": "Jawbone Visor",
  "name_zh": "颚骨面甲",
  "name_zh_tw": "顎骨面甲",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "扩展",
  "durability": 25,
  "defense_min": 55,
  "defense_max": 68,
  "defense_avg": 61.5,
  "reqstr": 58,
  "qlvl": 33,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/jawbone_cap.webp"
 },
 {
  "code": "ba7",
  "name_en": "Lion Helm",
  "name_zh": "狮牙头盔",
  "name_zh_tw": "獅牙頭盔",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "扩展",
  "durability": 35,
  "defense_min": 63,
  "defense_max": 75,
  "defense_avg": 69.0,
  "reqstr": 73,
  "qlvl": 38,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/fanged_helm.webp"
 },
 {
  "code": "ba8",
  "name_en": "Rage Mask",
  "name_zh": "狂怒面具",
  "name_zh_tw": "狂怒面具",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "扩展",
  "durability": 45,
  "defense_min": 78,
  "defense_max": 90,
  "defense_avg": 84.0,
  "reqstr": 88,
  "qlvl": 44,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/horned_helm.webp"
 },
 {
  "code": "ba9",
  "name_en": "Savage Helmet",
  "name_zh": "凶蛮头盔",
  "name_zh_tw": "凶蠻頭盔",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "扩展",
  "durability": 50,
  "defense_min": 85,
  "defense_max": 98,
  "defense_avg": 91.5,
  "reqstr": 103,
  "qlvl": 49,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/assault_helmet.webp"
 },
 {
  "code": "baa",
  "name_en": "Slayer Guard",
  "name_zh": "杀手护盔",
  "name_zh_tw": "殺手護盔",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "扩展",
  "durability": 55,
  "defense_min": 93,
  "defense_max": 120,
  "defense_avg": 106.5,
  "reqstr": 118,
  "qlvl": 54,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/avenger_guard.webp"
 },
 {
  "code": "pa6",
  "name_en": "Akaran Targe",
  "name_zh": "阿卡拉圆盾",
  "name_zh_tw": "阿卡拉圓盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 101,
  "defense_max": 125,
  "defense_avg": 113.0,
  "reqstr": 44,
  "qlvl": 35,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/targe.webp"
 },
 {
  "code": "pa7",
  "name_en": "Akaran Rondache",
  "name_zh": "阿卡拉轻圆盾",
  "name_zh_tw": "阿卡拉輕圓盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "扩展",
  "durability": 30,
  "defense_min": 113,
  "defense_max": 137,
  "defense_avg": 125.0,
  "reqstr": 59,
  "qlvl": 40,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/rondache.webp"
 },
 {
  "code": "pa8",
  "name_en": "Protector Shield",
  "name_zh": "守护之盾",
  "name_zh_tw": "守護之盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "扩展",
  "durability": 40,
  "defense_min": 129,
  "defense_max": 153,
  "defense_avg": 141.0,
  "reqstr": 69,
  "qlvl": 46,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/heraldic_shield.webp"
 },
 {
  "code": "pa9",
  "name_en": "Gilded Shield",
  "name_zh": "金纹盾",
  "name_zh_tw": "金紋盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "扩展",
  "durability": 50,
  "defense_min": 144,
  "defense_max": 168,
  "defense_avg": 156.0,
  "reqstr": 89,
  "qlvl": 51,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/aerin_shield.webp"
 },
 {
  "code": "paa",
  "name_en": "Royal Shield",
  "name_zh": "皇家盾",
  "name_zh_tw": "皇家盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "扩展",
  "durability": 60,
  "defense_min": 156,
  "defense_max": 181,
  "defense_avg": 168.5,
  "reqstr": 114,
  "qlvl": 55,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/crown_shield.webp"
 },
 {
  "code": "ne6",
  "name_en": "Mummified Trophy",
  "name_zh": "木乃伊首级",
  "name_zh_tw": "木乃伊首級",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 38,
  "defense_max": 48,
  "defense_avg": 43.0,
  "reqstr": 38,
  "qlvl": 33,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/preserved_head.webp"
 },
 {
  "code": "ne7",
  "name_en": "Fetish Trophy",
  "name_zh": "鬼娃首级",
  "name_zh_tw": "鬼娃首級",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 41,
  "defense_max": 52,
  "defense_avg": 46.5,
  "reqstr": 41,
  "qlvl": 39,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/zombie_head.webp"
 },
 {
  "code": "ne8",
  "name_en": "Sexton Trophy",
  "name_zh": "司事首级",
  "name_zh_tw": "司事首級",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 44,
  "defense_max": 55,
  "defense_avg": 49.5,
  "reqstr": 47,
  "qlvl": 45,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/unraveller_head.webp"
 },
 {
  "code": "ne9",
  "name_en": "Cantor Trophy",
  "name_zh": "领唱者首级",
  "name_zh_tw": "領唱者首級",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 50,
  "defense_max": 64,
  "defense_avg": 57.0,
  "reqstr": 50,
  "qlvl": 49,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/gargoyle_head.webp"
 },
 {
  "code": "nea",
  "name_en": "Heirophant Trophy",
  "name_zh": "祭司首级",
  "name_zh_tw": "祭司首級",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 58,
  "defense_max": 70,
  "defense_avg": 64.0,
  "reqstr": 58,
  "qlvl": 54,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/demon_head.webp"
 },
 {
  "code": "drb",
  "name_en": "Blood Spirit",
  "name_zh": "血系灵兽帽",
  "name_zh_tw": "血系靈獸帽",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "精英",
  "durability": 20,
  "defense_min": 101,
  "defense_max": 145,
  "defense_avg": 123.0,
  "reqstr": 86,
  "qlvl": 62,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/wolf_head.webp"
 },
 {
  "code": "drc",
  "name_en": "Sun Spirit",
  "name_zh": "日阳灵兽帽",
  "name_zh_tw": "日陽靈獸帽",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "精英",
  "durability": 20,
  "defense_min": 98,
  "defense_max": 147,
  "defense_avg": 122.5,
  "reqstr": 95,
  "qlvl": 69,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/hawk_helm.webp"
 },
 {
  "code": "drd",
  "name_en": "Earth Spirit",
  "name_zh": "地土灵兽帽",
  "name_zh_tw": "地土靈獸帽",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "精英",
  "durability": 20,
  "defense_min": 107,
  "defense_max": 152,
  "defense_avg": 129.5,
  "reqstr": 104,
  "qlvl": 76,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/antlers.webp"
 },
 {
  "code": "dre",
  "name_en": "Sky Spirit",
  "name_zh": "天翔灵兽帽",
  "name_zh_tw": "天翔靈獸帽",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "精英",
  "durability": 20,
  "defense_min": 103,
  "defense_max": 155,
  "defense_avg": 129.0,
  "reqstr": 113,
  "qlvl": 83,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/falcon_mask.webp"
 },
 {
  "code": "drf",
  "name_en": "Dream Spirit",
  "name_zh": "幽梦灵兽帽",
  "name_zh_tw": "幽夢靈獸帽",
  "category": "头盔",
  "type_raw": "pelt",
  "tier": "精英",
  "durability": 20,
  "defense_min": 109,
  "defense_max": 159,
  "defense_avg": 134.0,
  "reqstr": 118,
  "qlvl": 85,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/spirit_mask.webp"
 },
 {
  "code": "bab",
  "name_en": "Carnage Helm",
  "name_zh": "屠杀头盔",
  "name_zh_tw": "屠殺頭盔",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "精英",
  "durability": 25,
  "defense_min": 102,
  "defense_max": 147,
  "defense_avg": 124.5,
  "reqstr": 106,
  "qlvl": 60,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/jawbone_cap.webp"
 },
 {
  "code": "bac",
  "name_en": "Fury Visor",
  "name_zh": "暴怒面甲",
  "name_zh_tw": "暴怒面甲",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "精英",
  "durability": 35,
  "defense_min": 105,
  "defense_max": 150,
  "defense_avg": 127.5,
  "reqstr": 129,
  "qlvl": 66,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/fanged_helm.webp"
 },
 {
  "code": "bad",
  "name_en": "Destroyer Helm",
  "name_zh": "毁灭者头盔",
  "name_zh_tw": "毀滅者頭盔",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "精英",
  "durability": 45,
  "defense_min": 111,
  "defense_max": 156,
  "defense_avg": 133.5,
  "reqstr": 151,
  "qlvl": 73,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/horned_helm.webp"
 },
 {
  "code": "bae",
  "name_en": "Conqueror Crown",
  "name_zh": "征服者盔冠",
  "name_zh_tw": "征服者盔冠",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "精英",
  "durability": 50,
  "defense_min": 114,
  "defense_max": 159,
  "defense_avg": 136.5,
  "reqstr": 174,
  "qlvl": 80,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/assault_helmet.webp"
 },
 {
  "code": "baf",
  "name_en": "Guardian Crown",
  "name_zh": "守护者盔冠",
  "name_zh_tw": "守護者盔冠",
  "category": "头盔",
  "type_raw": "phlm",
  "tier": "精英",
  "durability": 55,
  "defense_min": 117,
  "defense_max": 168,
  "defense_avg": 142.5,
  "reqstr": 196,
  "qlvl": 85,
  "max_sockets": 3,
  "sockets3": "2/3/3",
  "speed": 0,
  "img": "assets/equipment/avenger_guard.webp"
 },
 {
  "code": "pab",
  "name_en": "Sacred Targe",
  "name_zh": "神圣小盾",
  "name_zh_tw": "神聖小盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "精英",
  "durability": 45,
  "defense_min": 126,
  "defense_max": 158,
  "defense_avg": 142.0,
  "reqstr": 86,
  "qlvl": 63,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/targe.webp"
 },
 {
  "code": "pac",
  "name_en": "Sacred Rondache",
  "name_zh": "神圣轻圆盾",
  "name_zh_tw": "神聖輕圓盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "精英",
  "durability": 68,
  "defense_min": 138,
  "defense_max": 164,
  "defense_avg": 151.0,
  "reqstr": 109,
  "qlvl": 70,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/rondache.webp"
 },
 {
  "code": "pad",
  "name_en": "Ancient Shield",
  "name_zh": "库拉斯特盾",
  "name_zh_tw": "庫拉斯特盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "精英",
  "durability": 55,
  "defense_min": 154,
  "defense_max": 172,
  "defense_avg": 163.0,
  "reqstr": 124,
  "qlvl": 74,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/heraldic_shield.webp"
 },
 {
  "code": "pae",
  "name_en": "Zakarum Shield",
  "name_zh": "撒卡兰姆盾",
  "name_zh_tw": "撒卡蘭姆盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "精英",
  "durability": 65,
  "defense_min": 169,
  "defense_max": 193,
  "defense_avg": 181.0,
  "reqstr": 142,
  "qlvl": 82,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/aerin_shield.webp"
 },
 {
  "code": "paf",
  "name_en": "Vortex Shield",
  "name_zh": "涡旋盾",
  "name_zh_tw": "渦旋盾",
  "category": "盾牌",
  "type_raw": "ashd",
  "tier": "精英",
  "durability": 90,
  "defense_min": 182,
  "defense_max": 225,
  "defense_avg": 203.5,
  "reqstr": 148,
  "qlvl": 85,
  "max_sockets": 4,
  "sockets3": "3/4/4",
  "speed": 0,
  "img": "assets/equipment/crown_shield.webp"
 },
 {
  "code": "neb",
  "name_en": "Minion Skull",
  "name_zh": "仆从颅骨",
  "name_zh_tw": "僕從顱骨",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "精英",
  "durability": 20,
  "defense_min": 95,
  "defense_max": 139,
  "defense_avg": 117.0,
  "reqstr": 77,
  "qlvl": 59,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/preserved_head.webp"
 },
 {
  "code": "neg",
  "name_en": "Hellspawn Skull",
  "name_zh": "地狱爪牙颅骨",
  "name_zh_tw": "地獄爪牙顱骨",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "精英",
  "durability": 20,
  "defense_min": 96,
  "defense_max": 141,
  "defense_avg": 118.5,
  "reqstr": 82,
  "qlvl": 67,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/zombie_head.webp"
 },
 {
  "code": "ned",
  "name_en": "Overseer Skull",
  "name_zh": "督军颅骨",
  "name_zh_tw": "督軍顱骨",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "精英",
  "durability": 20,
  "defense_min": 98,
  "defense_max": 142,
  "defense_avg": 120.0,
  "reqstr": 91,
  "qlvl": 66,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/unraveller_head.webp"
 },
 {
  "code": "nee",
  "name_en": "Succubus Skull",
  "name_zh": "魅魔颅骨",
  "name_zh_tw": "魅魔顱骨",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "精英",
  "durability": 20,
  "defense_min": 100,
  "defense_max": 146,
  "defense_avg": 123.0,
  "reqstr": 95,
  "qlvl": 81,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/gargoyle_head.webp"
 },
 {
  "code": "nef",
  "name_en": "Bloodlord Skull",
  "name_zh": "鲜血之王颅骨",
  "name_zh_tw": "鮮血之王顱骨",
  "category": "盾牌",
  "type_raw": "head",
  "tier": "精英",
  "durability": 20,
  "defense_min": 103,
  "defense_max": 148,
  "defense_avg": 125.5,
  "reqstr": 106,
  "qlvl": 85,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/demon_head.webp"
 },
 {
  "code": "wa1",
  "name_en": "Old Book",
  "name_zh": "旧书",
  "name_zh_tw": "舊書",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "普通",
  "durability": 20,
  "defense_min": 2,
  "defense_max": 5,
  "defense_avg": 3.5,
  "reqstr": 12,
  "qlvl": 4,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/oldbook.webp"
 },
 {
  "code": "wa2",
  "name_en": "Tome",
  "name_zh": "秘典",
  "name_zh_tw": "秘典",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "普通",
  "durability": 20,
  "defense_min": 4,
  "defense_max": 8,
  "defense_avg": 6.0,
  "reqstr": 14,
  "qlvl": 8,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/tome_book.webp"
 },
 {
  "code": "wa3",
  "name_en": "Codex",
  "name_zh": "宝典",
  "name_zh_tw": "寶典",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "普通",
  "durability": 20,
  "defense_min": 6,
  "defense_max": 10,
  "defense_avg": 8.0,
  "reqstr": 18,
  "qlvl": 16,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/codex.webp"
 },
 {
  "code": "wa4",
  "name_en": "Compendium",
  "name_zh": "纲要",
  "name_zh_tw": "綱要",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "普通",
  "durability": 20,
  "defense_min": 10,
  "defense_max": 16,
  "defense_avg": 13.0,
  "reqstr": 20,
  "qlvl": 20,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/compendium.webp"
 },
 {
  "code": "wa5",
  "name_en": "Grimoire",
  "name_zh": "魔典",
  "name_zh_tw": "魔典",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "普通",
  "durability": 20,
  "defense_min": 15,
  "defense_max": 20,
  "defense_avg": 17.5,
  "reqstr": 25,
  "qlvl": 24,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/grimoire.webp"
 },
 {
  "code": "wa6",
  "name_en": "Burnt Text",
  "name_zh": "焦灼书册",
  "name_zh_tw": "焦灼書冊",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 38,
  "defense_max": 48,
  "defense_avg": 43.0,
  "reqstr": 38,
  "qlvl": 33,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/oldbook.webp"
 },
 {
  "code": "wa7",
  "name_en": "Dark Tome",
  "name_zh": "黑暗秘典",
  "name_zh_tw": "黑暗秘典",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 41,
  "defense_max": 52,
  "defense_avg": 46.5,
  "reqstr": 41,
  "qlvl": 39,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/tome_book.webp"
 },
 {
  "code": "wa8",
  "name_en": "Dark Codex",
  "name_zh": "黑暗宝典",
  "name_zh_tw": "黑暗寶典",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 44,
  "defense_max": 55,
  "defense_avg": 49.5,
  "reqstr": 47,
  "qlvl": 45,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/codex.webp"
 },
 {
  "code": "wa9",
  "name_en": "Possessed Compendium",
  "name_zh": "著魔纲要",
  "name_zh_tw": "著魔綱要",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 50,
  "defense_max": 64,
  "defense_avg": 57.0,
  "reqstr": 50,
  "qlvl": 49,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/compendium.webp"
 },
 {
  "code": "waa",
  "name_en": "Possessed Grimoire",
  "name_zh": "著魔魔典",
  "name_zh_tw": "著魔魔典",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "扩展",
  "durability": 20,
  "defense_min": 58,
  "defense_max": 70,
  "defense_avg": 64.0,
  "reqstr": 58,
  "qlvl": 54,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/grimoire.webp"
 },
 {
  "code": "wab",
  "name_en": "Forgotten Volume",
  "name_zh": "被遗忘的书册",
  "name_zh_tw": "被遺忘的書冊",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "精英",
  "durability": 20,
  "defense_min": 95,
  "defense_max": 139,
  "defense_avg": 117.0,
  "reqstr": 77,
  "qlvl": 59,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/oldbook.webp"
 },
 {
  "code": "wac",
  "name_en": "Occult Tome",
  "name_zh": "神秘秘典",
  "name_zh_tw": "神秘秘典",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "精英",
  "durability": 20,
  "defense_min": 96,
  "defense_max": 141,
  "defense_avg": 118.5,
  "reqstr": 82,
  "qlvl": 67,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/tome_book.webp"
 },
 {
  "code": "wad",
  "name_en": "Occult Codex",
  "name_zh": "神秘宝典",
  "name_zh_tw": "神秘寶典",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "精英",
  "durability": 20,
  "defense_min": 98,
  "defense_max": 142,
  "defense_avg": 120.0,
  "reqstr": 91,
  "qlvl": 66,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/codex.webp"
 },
 {
  "code": "wae",
  "name_en": "Blasphemous Compendium",
  "name_zh": "亵渎纲要",
  "name_zh_tw": "褻瀆綱要",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "精英",
  "durability": 20,
  "defense_min": 100,
  "defense_max": 146,
  "defense_avg": 123.0,
  "reqstr": 95,
  "qlvl": 81,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/compendium.webp"
 },
 {
  "code": "waf",
  "name_en": "Blasphemous Grimoire",
  "name_zh": "亵渎魔典",
  "name_zh_tw": "褻瀆魔典",
  "category": "盾牌",
  "type_raw": "grim",
  "tier": "精英",
  "durability": 20,
  "defense_min": 103,
  "defense_max": 148,
  "defense_avg": 125.5,
  "reqstr": 106,
  "qlvl": 85,
  "max_sockets": 2,
  "sockets3": "2/2/2",
  "speed": 0,
  "img": "assets/equipment/grimoire.webp"
 }
];
